### ISSUE TITLE
у вас оно ещё работает?

### ISSUE THREAD

**Issue by whoizit** [dzhioev/vk_api_auth#2]
в print(doc) получаю

<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/0.3.33</center>
</body>

**Comment by dzhioev** [comment]
Не работало, но у меня ошибка была другая:

Traceback (most recent call last):
  File "./fetch_photos.py", line 49, in <module>
    token, user_id = vk_auth.auth(email, password, client_id, "photos")
  File "/tmp/vk_api_auth/vk_auth.py", line 92, in auth
    doc, url = auth_user(email, password, client_id, scope, opener)
  File "/tmp/vk_api_auth/vk_auth.py", line 70, in auth_user
    raise NotImplementedError("Method '%s'" % params.method)
NameError: global name 'params' is not defined

Сейчас поправил, и у меня все работает. Попробуйте последнюю версию.

**Comment by whoizit** [comment]
ну и у меня такая же ошибка была, я просто вывод того, что возвращается показал. А наверное стоило показать тот, что показали вы. Спасибо, вечером попробую

**Comment by whoizit** [comment]
Это не работает, я не знаю как вы правили, что у вас это работает, но ваши правки нужно сделать в коде библиотеки в двух местах, тогда заработает. Спасибо

**Comment by dzhioev** [comment]
Ничего не понял из вашего сообщения.

**Comment by whoizit** [comment]
строчки 80, 81 надо исправить так же как 67, 68 в коде библиотеки

**Comment by dzhioev** [comment]
Все, пофиксил.
